extends SceneTree
func _initialize() -> void:
	assert(FileAccess.file_exists("res://desktop_config.json"))
	var credits := FileAccess.get_file_as_string("res://CREDITS.md")
	assert(credits.contains("Open-Meteo") and credits.contains("https://creativecommons.org/licenses/by/4.0/"))
	assert(not FileAccess.file_exists("res://.godot/do_run_environment.cfg"))
	assert(not ResourceLoader.exists("res://addons/desktop_export/plugin.gd"))
	assert(not ResourceLoader.exists("res://addons/run_environment/plugin.gd"))
	assert(ResourceLoader.exists("res://scripts/client/world_chat.gd"))
	assert(ResourceLoader.exists("res://scripts/client/touch_controls.gd"))
	assert(ResourceLoader.exists("res://scripts/client/weather_effects.gd"))
	assert(ResourceLoader.exists("res://scripts/shared/chat_rules.gd"))
	assert(ResourceLoader.exists("res://scripts/shared/road_geometry.gd"))
	assert(ResourceLoader.exists("res://scripts/client/account_session.gd"))
	assert(ResourceLoader.exists("res://scripts/client/credential_store.gd"))
	assert(not ResourceLoader.exists("res://scripts/client/guest_session.gd"))
	assert(not ResourceLoader.exists("res://scripts/server/game_server.gd"))
	assert(not ResourceLoader.exists("res://scripts/campus_pack_loader.gd"))
	assert(not ResourceLoader.exists("res://scripts/campus_streamer.gd"))
	assert(not FileAccess.file_exists("res://campus_packs.json"))
	for id in ["lingshui","eda","panjin"]:
		var roads_path: String = "res://assets/campuses/"+id+"/data/osm_roads.json"
		assert(FileAccess.file_exists(roads_path))
		assert(not JSON.parse_string(FileAccess.get_file_as_string(roads_path)).roads.is_empty())
		var scene: Node = load("res://scenes/campuses/"+id+".tscn").instantiate()
		assert(scene.get_node("CampusModel").get_child_count()>0)
		assert(scene.has_node("Vegetation"))
		assert(not scene.get_node("Vegetation").find_children("*", "MultiMeshInstance3D", true, false).is_empty())
		assert(FileAccess.file_exists("res://assets/campuses/"+id+"/data/vegetation.json"))
		var manifest_path: String = "res://assets/campuses/"+id+"/data/campus.json"
		assert(FileAccess.file_exists(manifest_path))
		var manifest: Dictionary = JSON.parse_string(FileAccess.get_file_as_string(manifest_path))
		assert(not manifest.features.is_empty())
		if id == "lingshui":
			assert(scene.has_node("PhotoRoadDetails"))
			assert(scene.get_node("PhotoRoadDetails").find_children("*", "StaticBody3D", true, false).size() == 5)
		if id == "panjin":
			assert(manifest.features.size()==64)
		var precipitation := scene.get_node("CampusEnvironment/Precipitation")
		assert(precipitation.get_node("Rain") is GPUParticles3D)
		assert(precipitation.get_node("Snow") is GPUParticles3D)
		assert(precipitation.get_node("Shelter") is GPUParticlesCollisionHeightField3D)
		scene.free()
	assert(ResourceLoader.exists("res://assets/vegetation/leaves.gdshader"))
	assert(ResourceLoader.exists("res://assets/vegetation/bark_brown_02_diff_1k.jpg"))
	assert(not FileAccess.file_exists("res://../../references/eda/vegetation/planting.json"))
	print("PASS: desktop package has three full local campuses, API config and no server or Web download code")
	quit()
