name: CI

on:
  push:
    branches: ["**"]
    paths:
      - "apps/**"
      - "!apps/**/*.md"
      - ".github/workflows/**"
      - ".dockerignore"
      - ".gitattributes"
  pull_request:
    paths:
      - "apps/**"
      - "!apps/**/*.md"
      - ".github/workflows/**"
      - ".dockerignore"
      - ".gitattributes"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/test.yml
  web:
    needs: test
    if: needs.test.outputs.web == 'true'
    uses: ./.github/workflows/build-web.yml
  game:
    needs: test
    if: needs.test.outputs.game == 'true'
    uses: ./.github/workflows/build-game.yml
